services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: D1ymf8wyQEGthFR1E9xhCq
      POSTGRES_USER: LTIdbUser
      POSTGRES_DB: LTIdb
      # Ensure the user has superuser privileges
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - 5432:5432
